namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System.Collections.Immutable;
using System.Text;
using global::Microsoft.CodeAnalysis;

public static class MediatorExtensionTemplate
{
    public static void GenerateMediatorExtensionSource(
        SourceProductionContext ctx,
        ImmutableArray<(ITypeSymbol Request, ITypeSymbol Response, ITypeSymbol Handler)> requestHandlers,
        ImmutableArray<(ITypeSymbol Notification, ImmutableArray<ITypeSymbol> Handlers)> notificationHandlers,
        string @namespace)
    {
        if (requestHandlers.IsEmpty && notificationHandlers.IsEmpty)
        {
            return;
        }

        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine($$"""
            // <auto-generated>
            //    This code was generated by OtherMediator source generation.
            // </auto-generated>
            #nullable enable

            namespace {{@namespace}}.Extensions.Microsoft.DependencyInjection;

            using global::Microsoft.Extensions.DependencyInjection;
            using global::System.Runtime.ExceptionServices;
            using global::System;
            using global::System.Collections.Generic;
            using global::System.Linq;
            using global::{{@namespace}};
            using global::{{@namespace}}.Contracts;

            /// <summary>
            /// Extension methods to register OtherMediator services into the Microsoft
            /// dependency injection <see cref="IServiceCollection"/>.
            /// </summary>
            public static class GeneratedMediatorExtension
            {
                private static MediatorConfiguration _mediatorConfiguration;

                /// <summary>
                /// Gets the current <see cref="MediatorConfiguration"/> instance.
                /// </summary>
                public static global::{{@namespace}}.MediatorConfiguration MediatorConfiguration => _mediatorConfiguration ??= new global::{{@namespace}}.MediatorConfiguration();

                /// <summary>
                /// Adds OtherMediator to the provided <see cref="IServiceCollection"/>.
                /// </summary>
                public static IServiceCollection AddOtherMediator(this IServiceCollection services, Action<global::{{@namespace}}.MediatorConfiguration>? config = null)
                {
                    ArgumentNullException.ThrowIfNull(services);

                    var opt = new global::{{@namespace}}.MediatorConfiguration();
                    config?.Invoke(opt);

                    if (opt.UseExceptionHandler)
                    {
                        AddExceptionHandlerBehaviors(services);
                    }

                    _mediatorConfiguration = opt;

                    AddCoreMediator(services);

                    AddGeneratedHandlers(services, (global::Microsoft.Extensions.DependencyInjection.ServiceLifetime)opt.Lifetime);

                    return services;
                }

                private static void AddExceptionHandlerBehaviors(IServiceCollection services)
                {
            """);

        if (!requestHandlers.IsEmpty)
        {
            foreach (var (requestType, responseType, _) in requestHandlers)
            {
                var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                    services.TryAddSingleton(typeof(IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>), typeof(ErrorPipelineBehavior<{{requestFullName}}, {{responseFullName}}>));
                """);
            }
        }

        if (!notificationHandlers.IsEmpty)
        {
            foreach (var (notificationType, _) in notificationHandlers)
            {
                var notificationFullName = notificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                    services.TryAddSingleton(typeof(IPipelineBehavior<{{notificationFullName}}>), typeof(ErrorPipelineBehavior<{{notificationFullName}}>));
                """);
            }
        }

        sourceBuilder.AppendLine($$"""
                }

                private static void AddGeneratedHandlers(IServiceCollection services, ServiceLifetime lifetime)
                {
            """);

        if (!requestHandlers.IsEmpty)
        {
            foreach (var (requestType, responseType, handlerType) in requestHandlers)
            {
                var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                    services.TryAdd(new ServiceDescriptor(
                        typeof(IRequestHandler<{{requestFullName}}, {{responseFullName}}>),
                        typeof({{handlerFullName}}),
                        lifetime));
                """);
            }
        }

        sourceBuilder.AppendLine($$"""
                    
            """);

        if (!notificationHandlers.IsEmpty)
        {
            foreach (var (notificationType, handlers) in notificationHandlers)
            {
                var notificationFullName = notificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                foreach (var handlerType in handlers)
                {
                    var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    sourceBuilder.AppendLine($$"""
                    services.TryAdd(new ServiceDescriptor(
                        typeof(INotificationHandler<{{notificationFullName}}>),
                        typeof({{handlerFullName}}),
                        lifetime));
                    """);
                }
            }
        }

        sourceBuilder.AppendLine($$"""
                }

                private static void AddCoreMediator(IServiceCollection services)
                {
                    services.AddSingleton<IContainer>(sp => new GeneratedMicrosoftContainer(sp));

                    services.AddSingleton<IMediator>(sp =>
                    {
                        var container = sp.GetRequiredService<IContainer>();
                        return new GeneratedMediator(MediatorConfiguration, container);
                    });

                    services.AddSingleton<IPublisher>(sp => sp.GetRequiredService<IMediator>());
                    services.AddSingleton<ISender>(sp => sp.GetRequiredService<IMediator>());
                }

                /// <summary>
                /// Helper method to safely add a service if it doesn't already exist.
                /// </summary>
                private static void TryAdd(this IServiceCollection services, ServiceDescriptor descriptor)
                {
                    if (!services.Any(s => s.ServiceType == descriptor.ServiceType && s.ImplementationType == descriptor.ImplementationType))
                    {
                        services.Add(descriptor);
                    }
                }

                /// <summary>
                /// Helper method to safely add a singleton service.
                /// </summary>
                private static void TryAddSingleton(this IServiceCollection services, Type serviceType, Type implementationType)
                {
                    if (!services.Any(s => s.ServiceType == serviceType && s.ImplementationType == implementationType))
                    {
                        services.AddSingleton(serviceType, implementationType);
                    }
                }

                /// <summary>
                /// Registers an open generic pipeline behavior.
                /// </summary>
                public static IServiceCollection AddOpenPipelineBehavior(this IServiceCollection services, Type type)
                {
                    ArgumentNullException.ThrowIfNull(type);

                    var behaviorInterfaceRequest = type.GetInterfaces()
                        .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IPipelineBehavior<,>));

                    if (behaviorInterfaceRequest is not null)
                    {
                        services.TryAddSingleton(typeof(IPipelineBehavior<,>), type);
                    }

                    var behaviorInterfaceNotification = type.GetInterfaces()
                        .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IPipelineBehavior<>));

                    if (behaviorInterfaceNotification is not null)
                    {
                        services.TryAddSingleton(typeof(IPipelineBehavior<>), type);
                    }

                    return services;
                }

                /// <summary>
                /// Registers a pipeline behavior for a specific request/response type.
                /// </summary>
                public static IServiceCollection AddPipelineBehavior<TRequest, TResponse>(this IServiceCollection services, Type type)
                    where TRequest : IRequest<TResponse>
                {
                    ArgumentNullException.ThrowIfNull(type);

                    var serviceType = typeof(IPipelineBehavior<TRequest, TResponse>);
                    services.TryAddSingleton(serviceType, type);

                    return services;
                }

                /// <summary>
                /// Registers a pipeline behavior for a specific notification type.
                /// </summary>
                public static IServiceCollection AddPipelineBehavior<TNotification>(this IServiceCollection services, Type type)
                    where TNotification : INotification
                {
                    ArgumentNullException.ThrowIfNull(type);

                    var serviceType = typeof(IPipelineBehavior<TNotification>);
                    services.TryAddSingleton(serviceType, type);

                    return services;
                }
            }

            #pragma warning disable CS1591

            internal class ErrorPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
                where TRequest : IRequest<TResponse>
            {
                public async Task<TResponse> Handle(TRequest request, Func<TRequest, CancellationToken, Task<TResponse>> next, CancellationToken cancellationToken)
                {
                    try
                    {
                        return await next(request, cancellationToken);
                    }
                    catch (Exception ex)
                    {
                        ExceptionDispatchInfo.Capture(ex).Throw();
                        throw;
                    }
                }
            }

            internal class ErrorPipelineBehavior<TNotification> : IPipelineBehavior<TNotification>
                where TNotification : INotification
            {
                public async Task Handle(TNotification notification, Func<TNotification, CancellationToken, Task> next, CancellationToken cancellationToken)
                {
                    try
                    {
                        await next(notification, cancellationToken);
                    }
                    catch (Exception ex)
                    {
                        ExceptionDispatchInfo.Capture(ex).Throw();
                        throw;
                    }
                }
            }

            #pragma warning restore CS1591
            """);

        ctx.AddSource($"{@namespace}.Extensions.MediatorExtension.g.cs", sourceBuilder.ToString());
    }
}
