namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System.Collections.Immutable;
using System.Text;
using global::Microsoft.CodeAnalysis;

public static class MicrosoftContainerTemplate
{
    public static void GenerateMicrosoftContainerSource(
        SourceProductionContext ctx,
        ImmutableArray<(ITypeSymbol Request, ITypeSymbol Response, ITypeSymbol Handler)> requestHandlers,
        string @namespace)
    {
        if (requestHandlers.IsEmpty)
        {
            return;
        }

        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine($$"""
            // <auto-generated>
            //    This code was generated by OtherMediator source generation.
            // </auto-generated>
            #nullable enable

            namespace {{@namespace}}.Extensions.Microsoft.DependencyInjection;

            using global::Microsoft.Extensions.DependencyInjection;
            using global::System;
            using global::System.Collections.Generic;
            using global::System.Linq;
            using global::{{@namespace}};
            using global::{{@namespace}}.Contracts;

            /// <summary>
            /// Provides a concrete implementation of the <see cref="IContainer"/> abstraction
            /// that delegates all dependency resolution operations to the native Microsoft
            /// Dependency Injection (DI) system (<see cref="IServiceProvider"/>).
            /// </summary>
            /// <remarks>
            /// <para>
            /// This class acts as an <strong>adapter</strong> or <strong>bridge</strong> between the internal
            /// architecture of OtherMediator, which uses the <see cref="IContainer"/> abstraction,
            /// and the standard DI container of ASP.NET Core and .NET applications.
            /// </para>
            /// <para>
            /// <strong>Primary responsibilities:</strong>
            /// <list type="bullet">
            /// <item><description>Translate OtherMediator's resolution requests to calls to the Microsoft <see cref="IServiceProvider"/>.</description></item>
            /// <item><description>Fully preserve the lifecycle configurations (Singleton, Scoped, Transient) defined in the original DI container.</description></item>
            /// <item><description>Support both single service resolution and service collections resolution.</description></item>
            /// </list>
            /// </para>
            /// <para>
            /// <strong>Key characteristics:</strong>
            /// <list type="bullet">
            /// <item><description><strong>Transparency:</strong> Does not add additional instance management or lifecycle logic.</description></item>
            /// <item><description><strong>Native behavior:</strong> Exactly follows the resolution rules and behaviors of the underlying <see cref="IServiceProvider"/>.</description></item>
            /// <item><description><strong>Internal use:</strong> Designed primarily for use by OtherMediator's mediation system and not as a general-purpose Service Locator in application code.</description></item>
            /// </list>
            /// </para>
            /// </remarks>
            internal class GeneratedMicrosoftContainer(IServiceProvider serviceProvider) : IContainer
            {
                private readonly IServiceProvider _serviceProvider = serviceProvider;
                private readonly Dictionary<Type, object> _resolveCache = new();

                /// <inheritdoc />
                public T? Resolve<T>() where T : class
                {
                    return _serviceProvider.GetService<T>();
                }

                /// <inheritdoc />
                public IEnumerable<T>? Resolve<T>(Type type)
                {
                    var serviceType = typeof(IEnumerable<>).MakeGenericType(type);
                    return _serviceProvider.GetService(serviceType) as IEnumerable<T>;
                }

                /// <inheritdoc />
                public object? Resolve(Type type)
                {
                    return _serviceProvider.GetService(type);
                }

            """);

        foreach (var (requestType, responseType, handlerType) in requestHandlers)
        {
            var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sourceBuilder.AppendLine($$"""
                
                /// <summary>
                /// Resolves <see cref="{{handlerFullName}}"/> without reflection.
                /// </summary>
                public {{handlerFullName}}? Resolve_{{handlerType.Name}}()
                {
                    return _serviceProvider.GetService<{{handlerFullName}}>();
                }
                
                /// <summary>
                /// Resolves <see cref="IEnumerable{IPipelineBehavior{requestFullName}, {responseFullName}"/> without reflection.
                /// </summary>
                public IEnumerable<IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>>? 
                    Resolve_Pipelines_{{requestType.Name}}_{{responseType.Name}}()
                {
                    return _serviceProvider.GetService<IEnumerable<IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>>>();
                }
            """);
        }

        sourceBuilder.AppendLine("    }");

        ctx.AddSource($"{@namespace}.Extensions.MicrosoftContainer.g.cs", sourceBuilder.ToString());
    }
}
