using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

public static class NotificationSourceGenerationTemplate
{
    public static void GenerateNotificationSource(
        SourceProductionContext ctx,
        ImmutableArray<(ITypeSymbol Notification, ImmutableArray<ITypeSymbol> Handlers)> notificationData,
        string @namespace)
    {
        if (notificationData.IsEmpty)
        {
            return;
        }

        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine($$"""
            // <auto-generated>
            //    This code was generated by OtherMediator source generation.
            // </auto-generated>
            #nullable enable

            namespace {{@namespace}};

            using global::System;
            using global::System.Collections.Concurrent;
            using global::System.Collections.Generic;
            using global::System.Linq;
            using global::System.Threading;
            using global::System.Threading.Tasks;
            using global::{{@namespace}};
            using global::{{@namespace}}.Contracts;

            internal partial class GeneratedMediator : global::{{@namespace}}.Contracts.IMediator
            {

            """);

        foreach (var (notificationType, handlers) in notificationData)
        {
            var notificationFullName = notificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sourceBuilder.AppendLine($$"""
                
                /// <summary>
                /// Publish method for {{notificationType.Name}}
                /// </summary>
                public async Task Publish_{{notificationType.Name}}({{notificationFullName}} notification, CancellationToken cancellationToken = default)
                {
                    ArgumentNullException.ThrowIfNull(notification, nameof(notification));
                    
                    var delegates = GetOrAddPublishers_{{notificationType.Name}}(notification);
                    
                    var tasks = new List<Task>();
                    foreach (var handlerDelegate in delegates)
                    {
                        tasks.Add(handlerDelegate(notification, cancellationToken));
                    }
                    
                    if (_configuration.DispatchStrategy == DispatchStrategy.Parallel)
                    {
                        await Task.WhenAll(tasks);
                    }
                    
                    if (_configuration.DispatchStrategy == DispatchStrategy.Sequential)
                    {
                        foreach (var task in tasks)
                        {
                            cancellationToken.ThrowIfCancellationRequested();
                            await task;
                        }
                    }
                }
                
                private IEnumerable<Func<{{notificationFullName}}, CancellationToken, Task>> GetOrAddPublishers_{{notificationType.Name}}({{notificationFullName}} notification)
                {
                    return (IEnumerable<Func<{{notificationFullName}}, CancellationToken, Task>>)
                        _publishCache.GetOrAdd(notification, _ =>
                        {
                            var builtPipelines = new List<Func<{{notificationFullName}}, CancellationToken, Task>>();
                            
            """);

            // Generar resolución de cada handler
            foreach (var handlerType in handlers)
            {
                var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                            
                            var handler{{handlerType.Name}} = _container.Resolve<{{handlerFullName}}>();

                            if (handler{{handlerType.Name}} != null)
                            {
                                var pipelines{{handlerType.Name}} = _container.Resolve<IEnumerable<IPipelineBehavior<{{notificationFullName}}>>>();
                                var pipeline{{handlerType.Name}} = BuildPipeline_{{notificationType.Name}}_{{handlerType.Name}}(
                                    handler{{handlerType.Name}}, 
                                    pipelines{{handlerType.Name}} ?? Array.Empty<IPipelineBehavior<{{notificationFullName}}>>());
                                builtPipelines.Add(pipeline{{handlerType.Name}});
                            }
                """);
            }

            sourceBuilder.AppendLine($$"""
                            
                            return builtPipelines;
                        });
                }
                
            """);

            foreach (var handlerType in handlers)
            {
                var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                
                private static Func<{{notificationFullName}}, CancellationToken, Task> BuildPipeline_{{notificationType.Name}}_{{handlerType.Name}}(
                        {{handlerFullName}} handler,
                        IEnumerable<IPipelineBehavior<{{notificationFullName}}>> pipelines)
                {
                    Func<{{notificationFullName}}, CancellationToken, Task> pipeline = (request, ct) => ((dynamic)handler).Handle(request, ct);
                    
                    
                    foreach (var behavior in pipelines.Reverse())
                    {
                        var next = pipeline;
                        var b = behavior;
                        pipeline = (req, ct) => b.Handle(req, next, ct);
                    }
                        
                    return pipeline;
                }
                
                """);
            }
        }

        sourceBuilder.AppendLine($$"""
                
                public async Task Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default)
                    where TNotification : INotification
                {
                    ArgumentNullException.ThrowIfNull(notification, nameof(notification));
                    
                    switch (notification)
                    {
            """);

        foreach (var (notificationType, _) in notificationData)
        {
            var notificationFullName = notificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sourceBuilder.AppendLine($$"""
                case {{notificationFullName}} typedNotification:
                    await Publish_{{notificationType.Name}}(typedNotification, cancellationToken);
                    return;
            """);
        }

        sourceBuilder.AppendLine($$"""
                default:
                    throw new NotSupportedException($"Notification type {notification.GetType().Name} is not supported by generated mediator.");
                }
            }
        }

        """);

        ctx.AddSource($"{@namespace}.GeneratedMediator.Notifications.g.cs", sourceBuilder.ToString());
    }
}
