namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System.Collections.Immutable;
using System.Text;
using global::Microsoft.CodeAnalysis;

public static class OpenTelemetryExtensionsTemplate
{
    public static void GenerateOpenTelemetrySource(
        SourceProductionContext ctx,
        ImmutableArray<(ITypeSymbol Request, ITypeSymbol Response, ITypeSymbol Handler)> requestHandlers,
        ImmutableArray<(ITypeSymbol Notification, ImmutableArray<ITypeSymbol> Handlers)> notificationHandlers,
        string @namespace)
    {
        if (requestHandlers.IsEmpty && notificationHandlers.IsEmpty)
        {
            return;
        }

        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine($$"""
            // <auto-generated>
            //    This code was generated by OtherMediator source generation.
            // </auto-generated>
            #nullable enable

            namespace {{@namespace}}.Extensions.OpenTelemetry.Microsoft.DependencyInjection;

            using global::System.Linq;
            using global::Microsoft.Extensions.DependencyInjection;
            using global::Microsoft.Extensions.DependencyInjection.Extensions;
            using global::OpenTelemetry.Metrics;
            using global::OpenTelemetry.Trace;
            using global::{{@namespace}};
            using global::{{@namespace}}.Contracts;

            /// <summary>
            /// Provides extension methods for logging OpenTelemetry instrumentation
            /// related to OtherMediator in dependency containers and OpenTelemetry builders.
            /// </summary>
            public static class GeneratedOtherMediatorOpenTelemetryExtensions
            {
                private const string ServiceName = "OtherMediator";

                /// <summary>
                /// Registers the services required to instrument OtherMediator with OpenTelemetry.
                /// - Adds a singleton of <see cref="MediatorInstrumentation"/>.
                /// - Inserts <see cref="OpenTelemetryPipelineBehavior{TRequest,TResponse}"/> at the beginning
                /// of the pipeline behaviors collection for each registered request type.
                /// </summary>
                /// <param name="services">Service collection where instrumentation will be added.</param>
                /// <returns>The same instance of <see cref="IServiceCollection"/> to allow chaining.</returns>
                public static IServiceCollection AddMediatorOpenTelemetry(this IServiceCollection services)
                {
                    services.AddSingleton<MediatorInstrumentation>();

            """);

        if (!requestHandlers.IsEmpty)
        {
            foreach (var (requestType, responseType, _) in requestHandlers)
            {
                var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                    services.TryAddSingleton(typeof(IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>), typeof(OpenTelemetryPipelineBehavior<{{requestFullName}}, {{responseFullName}}>));
                """);
            }
        }

        if (!notificationHandlers.IsEmpty)
        {
            foreach (var (notificationType, _) in notificationHandlers)
            {
                var notificationFullName = notificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sourceBuilder.AppendLine($$"""
                    services.TryAddSingleton(typeof(IPipelineBehavior<{{notificationFullName}}>), typeof(OpenTelemetryPipelineBehavior<{{notificationFullName}}>));
                """);
            }
        }

        sourceBuilder.AppendLine($$"""
                    
                    return services;
                }

                /// <summary>
                /// Adds the OtherMediator trace source to the <see cref="TracerProviderBuilder"/>.
                /// Calls <see cref="TracerProviderBuilder.AddSource(string)"/> with the service name.
                /// </summary>
                /// <param name="builder">Tracer provider builder to which the source will be added.</param>
                /// <returns>The same <see cref="TracerProviderBuilder"/> to allow chaining.</returns>
                public static TracerProviderBuilder AddMediatorInstrumentation(this TracerProviderBuilder builder)
                {
                    builder.AddSource(ServiceName);
                    return builder;
                }

                /// <summary>
                /// Adds the OtherMediator meter to the <see cref="MeterProviderBuilder"/>.
                /// Calls <see cref="MeterProviderBuilder.AddMeter(string)"/> with the service name.
                /// </summary>
                /// <param name="builder">Meter provider builder to which the meter will be added.</param>
                /// <returns>The same <see cref="MeterProviderBuilder"/> to allow chaining.</returns>
                public static MeterProviderBuilder AddMediatorInstrumentation(this MeterProviderBuilder builder)
                {
                    builder.AddMeter(ServiceName);
                    return builder;
                }

                /// <summary>
                /// Helper method to safely add a service if it doesn't already exist.
                /// </summary>
                private static void TryAddSingleton<TService, TImplementation>(this IServiceCollection services)
                    where TService : class
                    where TImplementation : class, TService
                {
                    if (!services.Any(s => s.ServiceType == typeof(TService) && s.ImplementationType == typeof(TImplementation)))
                    {
                        services.AddSingleton<TService, TImplementation>();
                    }
                }
            }

            #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

            internal class MediatorInstrumentation
            {
                public const string SERVICE_NAME = "OtherMediator";
                
                public static readonly string[] GeneratedRequestTypes = new[]
                {
            """);

        if (!requestHandlers.IsEmpty)
        {
            var requestNames = requestHandlers
                .Select(h => $"\"{h.Request.Name}\"")
                .Distinct();

            sourceBuilder.AppendLine($"            {string.Join(",\n            ", requestNames)}");
        }

        sourceBuilder.AppendLine($$"""
                };

                public static readonly string[] GeneratedNotificationTypes = new[]
                {
            """);

        if (!notificationHandlers.IsEmpty)
        {
            var notificationNames = notificationHandlers
                .Select(n => $"\"{n.Notification.Name}\"")
                .Distinct();

            sourceBuilder.AppendLine($"            {string.Join(",\n            ", notificationNames)}");
        }

        sourceBuilder.AppendLine($$"""
                };
            }

            internal class OpenTelemetryPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
                where TRequest : IRequest<TResponse>
            {
                public async Task<TResponse> Handle(TRequest request, Func<TRequest, CancellationToken, Task<TResponse>> next, CancellationToken cancellationToken)
                {
                    return await next(request, cancellationToken);
                }
            }

            internal class OpenTelemetryPipelineBehavior<TNotification> : IPipelineBehavior<TNotification>
                where TNotification : INotification
            {
                public async Task Handle(TNotification notification, Func<TNotification, CancellationToken, Task> next, CancellationToken cancellationToken)
                {
                    await next(notification, cancellationToken);
                    return;
                }
            }

            #pragma warning restore CS1591
            """);

        ctx.AddSource($"{@namespace}.Extensions.OpenTelemetry.g.cs", sourceBuilder.ToString());
    }
}
