namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System;
using System.Collections.Immutable;
using global::Microsoft.CodeAnalysis;

public class OtherMediatorStartupTemplate
{
    public static Action<SourceProductionContext, ImmutableArray<T>> GetTemplateAction<T>(string @namespace) =>
        (ctx, arg) =>
        {
            if (arg.IsEmpty)
            {
                return;
            }

            var source =
                $$"""
                // <auto-generated>
                //    This code was generated by OtherMediator source generation.
                // </auto-generated>
                #nullable enable

                namespace {{@namespace}};

                using global::System;
                using global::Microsoft.Extensions.DependencyInjection;
                using global::OtherMediator.Extensions.Microsoft.DependencyInjection;
                using global::OtherMediator;
                using global::OtherMediator.Contracts;
                using global::Microsoft.AspNetCore.Hosting;
                using global::Microsoft.AspNetCore.Builder;
                using global::Microsoft.Extensions.Hosting;

                public class OtherMediatorWarmStartupFilter : IStartupFilter
                {
                    public Action<global::Microsoft.AspNetCore.Builder.IApplicationBuilder> Configure(Action<global::Microsoft.AspNetCore.Builder.IApplicationBuilder> next)
                    {
                        return builder =>
                        {
                {{string.Join("\n", arg.SelectMany((handler, index) =>
                    {
                        var handlerInterfaces = ((ITypeSymbol)handler!).AllInterfaces.ToList();

                        var implementationFullName = ((ITypeSymbol)handler).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                        return handlerInterfaces.Select(handlerInterface =>
                        {
                            var interfaceFullName = handlerInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                            if (!interfaceFullName.StartsWith(@namespace))
                            {
                                return null;
                            }

                            if(handlerInterface.TypeArguments.Length == 0)
                            {
                                throw new InvalidOperationException($"Handler interface '{{interfaceFullName}}' does not have type arguments.");
                            }

                            if(handlerInterface.TypeArguments.Length == 1)
                            {
                                var arg0 = handlerInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                                return $$"""
                                            var notificationHandler_{{index}} = ({{interfaceFullName}})builder.ApplicationServices.GetService(typeof({{interfaceFullName}}));
                                            //var behaviors_{{index}} = (IEnumerable<IPipelineBehavior<{{arg0}}>>)builder.ApplicationServices.GetServices(typeof(IPipelineBehavior<{{arg0}}>));
                                            IEnumerable<IPipelineBehavior<{{arg0}}>> t_{{index}} = new List<IPipelineBehavior<{{arg0}}>>();
                                            //WarmMediator.WarmNotificationHandlers<{{arg0}}>(notificationHandler_{{index}}, t_{{index}});
                                            if (notificationHandler_{{index}} is not null)
                                            {
                                                WarmMediator.WarmNotificationHandlers<{{arg0}}>(notificationHandler_{{index}}, t_{{index}});
                                            }
                                """;
                            }
                            else
                            {
                                var arg0 = handlerInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
                                var arg1 = handlerInterface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                                return $$"""
                                            var requestHandler_{{index}} = builder.ApplicationServices.GetService<{{interfaceFullName}}>();
                                            //var behaviors_{{index}} = builder.ApplicationServices.GetServices<IPipelineBehavior<{{arg0}}, {{arg1}}>>();
                                            IEnumerable<IPipelineBehavior<{{arg0}}, {{arg1}}>> t_{{index}} = new List<IPipelineBehavior<{{arg0}}, {{arg1}}>>();
                                            //WarmMediator.WarmRequestHandlers<{{arg0}}, {{arg1}}>(requestHandler_{{index}}, t_{{index}});
                                            if (requestHandler_{{index}} is not null)
                                            {
                                                WarmMediator.WarmRequestHandlers<{{arg0}}, {{arg1}}>(requestHandler_{{index}}, t_{{index}});
                                            }

                                """;
                            }
                        });
                    }
                ))}}

                            next(builder);
                        };
                    }
                }

                """;

            ctx.AddSource($"{@namespace}.StartupFilter.g.cs", source);
        };
}
