namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System.Collections.Immutable;
using System.Text;
using global::Microsoft.CodeAnalysis;

public static class SenderSourceGenerationTemplate
{
    public static void GenerateMediatorSource(
        SourceProductionContext ctx,
        ImmutableArray<(ITypeSymbol Request, ITypeSymbol Response, ITypeSymbol Handler)> handlerData,
        string @namespace)
    {
        if (handlerData.IsEmpty)
        {
            return;
        }

        var sourceBuilder = new StringBuilder();

        // Cabecera del archivo
        sourceBuilder.AppendLine($$"""
            // <auto-generated>
            //    This code was generated by OtherMediator source generation.
            // </auto-generated>
            #nullable enable

            namespace {{@namespace}};

            using global::System;
            using global::System.Collections.Concurrent;
            using global::System.Collections.Generic;
            using global::System.Linq;
            using global::System.Threading;
            using global::System.Threading.Tasks;
            using global::{{@namespace}};
            using global::{{@namespace}}.Contracts;

            internal partial class GeneratedMediator : global::{{@namespace}}.Contracts.IMediator
            {
                private readonly ConcurrentDictionary<(Type Request, Type Response), Func<object, CancellationToken, Task<object>>> _objectSenderCache = new();
                private readonly ConcurrentDictionary<INotification, IEnumerable<Delegate>> _publishCache = new();
                
                private readonly IMediatorConfiguration _configuration;
                private readonly IContainer _container;

                public GeneratedMediator(IMediatorConfiguration configuration, IContainer container)
                {
                    _configuration = configuration;
                    _container = container;
                }

            """);

        foreach (var (requestType, responseType, handlerType) in handlerData)
        {
            var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sourceBuilder.AppendLine($$"""
                
                /// <summary>
                /// Send method for {{requestType.Name}} -> {{responseType.Name}}
                /// </summary>
                public async Task<{{responseFullName}}> Send_{{requestType.Name}}_{{responseType.Name}}({{requestFullName}} request, CancellationToken cancellationToken = default)
                {
                    ArgumentNullException.ThrowIfNull(request, nameof(request));
                    
                    var key = (typeof({{requestFullName}}), typeof({{responseFullName}}));
                    
                    var invoker = _objectSenderCache.GetOrAdd(key, _ =>
                    {
                        var handler = _container.Resolve<{{handlerFullName}}>();
                        
                        if (handler is null)
                        {
                            throw new InvalidOperationException($"Make sure to register an {{handlerFullName}} in the dependency container.");
                        }
                        
                        var pipelines = _container.Resolve<IEnumerable<IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>>>();
                        
                        var pipeline = BuildPipeline_{{requestType.Name}}_{{responseType.Name}}(handler, pipelines ?? Array.Empty<IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>>());
                        
                        return async (reqObj, ct) =>
                        {
                            var req = ({{requestFullName}})reqObj!;
                            var res = await pipeline(req, ct).ConfigureAwait(false);
                            return (object)res!;
                        };
                    });
                    
                    var result = await invoker(request, cancellationToken);
                    return ({{responseFullName}})result!;
                }

                private static Func<{{requestFullName}}, CancellationToken, Task<{{responseFullName}}>> BuildPipeline_{{requestType.Name}}_{{responseType.Name}}(
                        {{handlerFullName}} handler,
                        IEnumerable<IPipelineBehavior<{{requestFullName}}, {{responseFullName}}>> pipelines)
                {
                    Func<{{requestFullName}}, CancellationToken, Task<{{responseFullName}}>> pipeline = (request, ct) => ((dynamic)handler).Handle(request, ct);

                    foreach (var behavior in pipelines.Reverse())
                    {
                        var next = pipeline;
                        var b = behavior;
                        pipeline = (req, ct) => b.Handle(req, next, ct);
                    }
                    
                    return pipeline;
                }

            """);
        }

        sourceBuilder.AppendLine($$"""
                
                public async Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)
                {
                    ArgumentNullException.ThrowIfNull(request, nameof(request));
                    
                    switch (request)
                    {
            """);

        foreach (var (requestType, responseType, handlerType) in handlerData)
        {
            var requestFullName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var responseFullName = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sourceBuilder.AppendLine($$"""
                    case {{requestFullName}} typedRequest:
                        return (TResponse)(object)await Send_{{requestType.Name}}_{{responseType.Name}}(typedRequest, cancellationToken);
            """);
        }

        sourceBuilder.AppendLine($$"""
                    default:
                        throw new NotSupportedException($"Request type {request.GetType().Name} is not supported by generated mediator.");
                    }
                }
            }

            """);

        ctx.AddSource($"{@namespace}.GeneratedMediator.Sender.g.cs", sourceBuilder.ToString());
    }
}
