namespace OtherMediator.Microsoft.SourceGenerator.Templates;

using System.Collections.Immutable;
using global::Microsoft.CodeAnalysis;

public class OtherMediatorServiceCollectionTemplate
{
    public static Action<SourceProductionContext, ImmutableArray<T>> GetTemplateAction<T>(string @namespace) =>
        (ctx, arg) =>
        {
            if (arg.IsEmpty)
            {
                return;
            }

            var source =
                $$"""
                // <auto-generated/>
                #nullable enable

                namespace {{@namespace}};

                using global::System;
                using global::Microsoft.Extensions.DependencyInjection;
                using global::OtherMediator.Extensions.Microsoft.DependencyInjection;
                using global::OtherMediator;
                using global::OtherMediator.Contracts;

                internal static class OtherMediatorServiceCollectionExtensions
                {
                    /// <summary>
                    /// Adds OtherMediator and its handlers to the service collection.
                    /// </summary>
                    /// <param name="services">The service collection.</param>
                    /// <param name="config">An optional configuration action for the mediator.</param>
                    /// <returns>The service collection for chaining.</returns>
                    public static IServiceCollection AddOtherMediator(this IServiceCollection services, Action<MediatorConfiguration>? config = null)
                    {
                        services.AddMediator(config);

                {{string.Join("\n", arg.SelectMany(handler =>
                    {
                        var handlerInterfaces = ((ITypeSymbol)handler!).AllInterfaces.ToList();

                        return handlerInterfaces.Select(handlerInterface =>
                        {
                            var interfaceFullName = handlerInterface.ToDisplayString(
                                SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
                            var implementationFullName = ((ITypeSymbol)handler).ToDisplayString(
                                SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                            return $"        services.Add(new ServiceDescriptor(typeof({interfaceFullName}), typeof({implementationFullName}), (ServiceLifetime)MediatorExtension.MediatorConfiguration.Lifetime));";
                        });
                    }
                ))}}

                        return services;
                    }
                }

                """;

            ctx.AddSource($"{@namespace}.ServiceCollectionExtensions.g.cs", source);
        };
}
